name: Deploy to Render

on:
  workflow_run:
    workflows: ["Codacy CI"]  # nombre exacto del workflow de tests
    types:
      - completed
jobs:
  deploy:
    name: Deploy to Render
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Deploy to Render
        env:
          deploy_url: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
        run: |
          curl "$deploy_url"

